#!/usr/bin/env python3
import pygame
from pygame.locals import *
from elements import *

# window
WINDOW_SIZE = [800, 600]
WINDOW_CAPTION = "deus-pong"
SCOREBOX_WIDTH, SCOREBOX_HEIGHT = 0, 0
BORDER_MARGIN = 10

# visual
PAUSE_TEXT = "GAME PAUSED"
TERMINAL_RED = "\x1b[38;2;255;0;0m"
TERMINAL_NC = "\033[0m"
# TODO: more themes
COLOURSCHEMES = {
    "default": ((0, 0, 0), (255, 255, 255), (50, 50, 50))
}

# dynamic elements configuration
WIN_SCORE = 8
PADDLE_WIDTH, PADDLE_HEIGHT = 20, 100
PADDLE_MAX_VEL = 5
BALL_RADIUS = 7
BALL_MAX_VEL = 6

# pygame basics
SCREEN = pygame.display.set_mode(WINDOW_SIZE)

# pygame elements (horrible formatting)
PADDLE1 = Paddle(SCREEN, (0, WINDOW_SIZE[1] // 2 - PADDLE_HEIGHT // 2), PADDLE_MAX_VEL, (PADDLE_WIDTH, PADDLE_HEIGHT), COLOURSCHEMES["default"][1])
PADDLE2 = Paddle(SCREEN, (WINDOW_SIZE[0] - PADDLE_WIDTH, WINDOW_SIZE[1] // 2 - PADDLE_HEIGHT // 2), PADDLE_MAX_VEL, (PADDLE_WIDTH, PADDLE_HEIGHT), COLOURSCHEMES["default"][1])
BALL = Ball(SCREEN, (WINDOW_SIZE[0] // 2, WINDOW_SIZE[1] // 2), BALL_RADIUS, BALL_MAX_VEL, COLOURSCHEMES["default"][1])

SCOREBOARD = Scoreboard(SCREEN, WINDOW_SIZE, COLOURSCHEMES["default"])

PAUSE_MENU = PauseMenu(SCREEN, WINDOW_SIZE, PAUSE_TEXT, (WINDOW_SIZE[0] // 2, WINDOW_SIZE[1] // 2), COLOURSCHEMES["default"])
PAUSE_COL_RECT = Rect(WINDOW_SIZE[0] // 2 - 55, WINDOW_SIZE[1] - BORDER_MARGIN - 30, 25, 20)
CONTINUE_COL_RECT = Rect(WINDOW_SIZE[0] // 2 + 30, WINDOW_SIZE[1] - BORDER_MARGIN - 30, 25, 20)

PAUSE_BUTTON_RECT1 = (WINDOW_SIZE[0] // 2 - 55, WINDOW_SIZE[1] - BORDER_MARGIN - 30, 10, 20)
PAUSE_BUTTON_RECT2 = (WINDOW_SIZE[0] // 2 - 40, WINDOW_SIZE[1] - BORDER_MARGIN - 30, 10, 20)
CONTINUE_TRIGON_POINTS = ((WINDOW_SIZE[0] // 2 + 30, WINDOW_SIZE[1] - BORDER_MARGIN - 30), (WINDOW_SIZE[0] // 2 + 30,
                          WINDOW_SIZE[1] - BORDER_MARGIN - 10), (WINDOW_SIZE[0] // 2 + 55, WINDOW_SIZE[1] - BORDER_MARGIN - 20))
